### PR TITLE
Added message parts

### PR DESCRIPTION
**Pull request by Daivuk**
This allows the game to format the text the way it wants. For example: Coloring
The plain text is passed as usual. Added is the message parts from the JSONText, if available.

### CODE REVIEW

**Comment by N00byKing** [comment]
Hi,
first of all thanks for the PR, its nice to see other people interested ^^
However, I'm confused about what this adds to the library.
Does this enable something that was not possible to do before?
The data within the message parts was already accessible through
the specific AP_<TYPE>Message structs, no?
SM64 does this [here](https://github.com/N00byKing/sm64ex/blob/e070e04ea1699ada2a7ff0089e77cd9504559b37/src/sm64ap.cpp#L436) in order to introduce a more minimal formatting due to limited space, for reference.

**Comment by Daivuk** [comment]
Hi N00byKing,

The message parts are not available to the user of the lib. You are constructing the string inside the library:
```cpp
msg->text = std::string("Item ") + msg->item + std::string(" from ") + msg->sendPlayer + std::string(" to ") + msg->recvPlayer + std::string(" at ") + msg->location + std::string((msg->checked ? " (Checked)" : " (Unchecked)"));
```
The end user only gets a plain text. I see in SM64 you are reconstructing the string again. Doesn't this duplicate code? I wanted my game to just have to loop the parts, and chose the right color depending on the part type.
In example, in DOOM I do this:
```cpp
if (msg->messageParts.empty()) {
    colored_msg = "~2" + msg->text;
} else {
    for (const auto& message_part : msg->messageParts) {
        switch (message_part.type) {
            case AP_NormalText:
                colored_msg += "~2" + message_part.text;
                break;
            case AP_LocationText:
                colored_msg += "~3" + message_part.text;
                break;
            case AP_ItemText:
                colored_msg += "~7" + message_part.text;
                break;
            case AP_PlayerText:
                colored_msg += "~4" + message_part.text;
                break;
        }
    }
}
```
`~#` are color codes.

But now I am realizing; we could take this a step further. The JSON received from AP looks like this:
```json
[{
	"cmd": "PrintJSON",
	"data": [{
		"text": "1",
		"type": "player_id"
	}, {
		"text": " found their "
	}, {
		"text": "350076",
		"player": 1,
		"flags": 0,
		"type": "item_id"
	}, {
		"text": " ("
	}, {
		"text": "351018",
		"player": 1,
		"type": "location_id"
	}, {
		"text": ")"
	}],
	"type": "ItemSend",
	"receiving": 1,
	"item": {
		"item": 350076,
		"location": 351018,
		"player": 1,
		"flags": 0,
		"class": "NetworkItem"
	}
}]
```
This already contains the text and types. We could replace the IDs with text, then build the message parts from this instead.

**Comment by N00byKing** [comment]
While the specific wording parts ("{X} {got} {Y} {from} {Z}") is not available from the client lib, tha data (Player X, Item Y, Player Z, Type: ItemSend) is, which is what I meant, sorry.

ID to String parsing already happens, for example for unknown or unhandled message types.

The current implementation seperates the string that I used as a default into message parts, if I understand correctly. However, I am not a fan of this as it is not the same as the definition given in the network protocol for JSONMessageParts.
We could add a struct member that is just that; the parts as received by the server. This would go in the generic AP_Message struct as it is common to all message types.
But I don't want to encourage using these, instead the seperate message type structs should as the json message parts include text formatting, which should be on the part of the game client. The only reason a default string is in APCpp messages is for simplicity; allowing easier implementations.

If you *really* want the availability of the JSON Message parts, I would merge a PR adding these in. But I think that most use cases that that would help are already possible, in a way that I personally would prefer.

**Comment by Daivuk** [comment]
I made this on game-side now.

**Comment by Daivuk** [comment]
But I still believe this is the right thing. Because AP could construct messages with multiple parts without us having to update the games.

**Pull request closed without merging**
